apiVersion: apps/v1
kind: Deployment
metadata:
  name: partya
  labels:
    app: partya
spec:
  replicas: 1
  selector:
    matchLabels:
      app: partya
  template:
    metadata:
      labels:
        app: partya

    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - image: cordapps:4.8.6
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 1000
          name: corda
          imagePullPolicy: Never # to pull from local image
          # To delete an image from minikube do the following
          #  minikube image rm docker.io/library/corda:4.8.6
          #  minikube image load docker.io/library/corda:4.8.6
          env:
            - name: NODE_NAME
              value: partya
            - name: JVM_ARGS
              value: "-XX:+HeapDumpOnOutOfMemoryError -Djava.util.logging.config.file=/opt/corda/drivers/jdk_logging.properties -Dlog4j.configurationFile=/etc/corda/log4j2.xml -cp /opt/corda/drivers/log4j-layout-template-json-2.17.1.jar -javaagent:/opt/corda/drivers/jmx_prometheus_javaagent-0.16.1.jar=8080:/opt/corda/drivers/prom_jmx_exporter.yaml"
          ports:
            - containerPort: 10003 # P2P PORT
            - containerPort: 10004 # RPC PORT
            - containerPort: 2222 # ssh
          volumeMounts:
            - mountPath: /opt/corda/additional-node-infos/nodeInfo-7B8AF0AFE12D3B3993C45192A142CF0C30CC712BD66A8EF34F152A377D07AFEB
              name: vol1
              subPath: addtional-node1
            - mountPath: /opt/corda/additional-node-infos/nodeInfo-777DA369F066FE34BEDE3E6334A1006A4026A02DD76AFA798204BD015C9965DE
              name: vol1
              subPath: addtional-node2
            # - mountPath: /opt/corda/additional-node-infos/nodeInfo-E4477B559304AADFC0638772C0956A38FA2E2A7A5EB0E65D0D83E5884831879A
            #   name: vol1
            #   subPath: addtional-node3
            - mountPath: /etc/corda/node.conf
              name: secret-vol
              subPath: conf
            - mountPath: /opt/corda/network-parameters
              name: vol1
              subPath: network-parameters
            - mountPath: /opt/corda/certificates/nodekeystore.jks
              name: secret-vol
              subPath: nodekeystore
            - mountPath: /opt/corda/certificates/sslkeystore.jks
              name: secret-vol
              subPath: sslkeystore
            - mountPath: /opt/corda/certificates/truststore.jks
              name: secret-vol
              subPath: truststore
            - mountPath: /etc/corda/log4j2.xml
              name: vol1
              subPath: log4j2
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
            - name: logs
              mountPath: /opt/corda/logs
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: partya-pvc
        - name: varlog
          hostPath:
            path: /var/log
        - name: logs
          emptyDir: {}
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: secret-vol
          secret:
            secretName: partya-secrets
        - configMap:
            items:
              - key: addtional-node1
                path: addtional-node1
              - key: addtional-node2
                path: addtional-node2
              - key: addtional-node3
                path: addtional-node3
              - key: network-parameters
                path: network-parameters
              - key: persistenceMvDb
                path: persistenceMvDb
              - key: persistenceTraceDb
                path: persistenceTraceDb
              - key: node-info
                path: node-info
              - key: log4j2
                path: log4j2
            name: partya-conf
          name: vol1
---
apiVersion: v1
kind: Service
metadata:
  name: partya
spec:
  clusterIP: None
  ports:
    - port: 10003
      targetPort: 10003
      name: p2p
    - port: 10004
      targetPort: 10004
      name: rpc
    - port: 2222
      targetPort: 2222
      name: sshd
  selector:
    app: partya
