apiVersion: apps/v1
kind: Deployment
metadata:
  name: partya
  labels:
    app: partya
spec:
  replicas: 1
  selector:
    matchLabels:
      app: partya
  template:
    metadata:
      labels:
        app: partya
    spec:
      containers:
      - image: corda:4.8.6
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
        name: corda
        imagePullPolicy: Never    # to pull from local image
        # To delete an image from minikube do the following
        #  minikube image rm docker.io/library/corda:4.8.6   
        #  minikube image load docker.io/library/corda:4.8.6   
        ports:
          - containerPort: 10003 # P2P PORT
          - containerPort: 10004 # RPC PORT
          # - containerPort: 10005 # ssh
          - containerPort: 2222 # ssh
    # MY_P2P_PORT=10200 \
    # MY_RPC_PORT=10201 \
    # MY_RPC_ADMIN_PORT=10202 \          
        # resources:
        #   requests:
        #     memory: "1Gi"
        #     cpu: "500m"
        #   limits:
        #     memory: "2Gi"
        #     cpu: "1000m"
        volumeMounts:
        - mountPath: /opt/corda/additional-node-infos/nodeInfo-7B8AF0AFE12D3B3993C45192A142CF0C30CC712BD66A8EF34F152A377D07AFEB
          name: vol1
          subPath: addtional-node1
        - mountPath: /opt/corda/additional-node-infos/nodeInfo-777DA369F066FE34BEDE3E6334A1006A4026A02DD76AFA798204BD015C9965DE
          name: vol1
          subPath: addtional-node2
        # - mountPath: /opt/corda/additional-node-infos/nodeInfo-E4477B559304AADFC0638772C0956A38FA2E2A7A5EB0E65D0D83E5884831879A
        #   name: vol1
        #   subPath: addtional-node3
        - mountPath: /etc/corda/node.conf
          name: vol1
          subPath: conf
        - mountPath: /opt/corda/network-parameters
          name: vol1
          subPath: network-parameters
        - mountPath: /opt/corda/certificates/nodekeystore.jks
          name: vol1
          subPath: nodekeystore
        - mountPath: /opt/corda/certificates/sslkeystore.jks
          name: vol1
          subPath: sslkeystore
        - mountPath: /opt/corda/certificates/truststore.jks
          name: vol1
          subPath: truststore
      volumes:
      # - name: notary-pv
      #   persistentVolumeClaim:
      #     claimName: notary-pvc
      - configMap:
          items:
            - key: addtional-node1
              path: addtional-node1
            - key: addtional-node2
              path: addtional-node2
            - key: addtional-node3
              path: addtional-node3
            - key: conf
              path: conf
            - key: network-parameters
              path: network-parameters
            - key: persistenceMvDb
              path: persistenceMvDb
            - key: persistenceTraceDb
              path: persistenceTraceDb
            - key: node-info
              path: node-info
            - key: nodekeystore
              path: nodekeystore
            - key: sslkeystore
              path: sslkeystore
            - key: truststore
              path: truststore
          name: partya-conf
        name: vol1
    