apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: partya-pvc
  namespace: corda
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "2Gi"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: partya-pv
  labels:
    type: local
spec:
  capacity:
    storage: "2Gi"
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  hostPath:
    path: /corda/partya
